### ISSUE TITLE
Parsing error for comments with `args` or `syntax`

### ISSUE THREAD

**Issue by karldw** [kylebarron/language-stata#107]
Comments in `args` and `syntax` are highlighted in red, as if they're incorrect. These are acceptable stata code, as far as I can tell.

```stata
program program_name
    args a // this is a comment
    disp "`a'"
end

program other_program
    syntax [, a(integer 1)] // this is too
    disp "`a'"
end
```
![screenshot from 2019-02-13 12-25-48](https://user-images.githubusercontent.com/12504708/52741577-88e1c300-2f8a-11e9-93a0-4f57ef6f76cc.png)

Related: #94, #96

**Comment by kylebarron** [comment]
The latter was fixed in this morning's release; the previous was just fixed

**Comment by karldw** [comment]
Thank you!
