### ISSUE TITLE
invalid syntax when run multiple lines in Hydrogen

### ISSUE THREAD

**Issue by robsunch** [kylebarron/language-stata#111]
I use Hydrogen + stata_kernel + language-stata in Atom on two Windows machines. On Machine 1, when I run multiple lines of code with ctrl + Enter, I receive the "invalid syntax" error:
![image](https://user-images.githubusercontent.com/11682269/82108993-82ca2b80-9765-11ea-86c5-28bc5b53d4a3.png)
Running the code line by line is fine. However, on Machine 2, I can run multiple lines of code without any problem.  Does anyone know what may have caused such behavior on Machine 1?

Here are the details of my setup on Machine 1 (where the problem occurs) and Machine 2:

**Machine 1**
Microsoft Windows, Version 1903 (OS Build 18362.836)
Atom setups:
apm  2.4.3
npm  6.2.0
node 10.2.1 x64
atom 1.46.0
python
git 2.25.0.windows.1
visual studio

atom packages:
├── file-icons@2.1.41
├── highlight-selected@0.17.0
├── Hydrogen@2.14.1
├── hyperclick@0.1.5
├── indent-detective@0.4.0
├── ink@0.12.3
├── julia-client@0.12.4
├── language-batch@0.4.0
├── language-julia@0.19.3
├── language-stata@1.7.3
├── latex-completions@0.3.6
├── move-panes@0.2.0
├── script@3.26.0
├── scroll-marker@0.3.2
├── tool-bar@1.3.0
└── uber-juno@0.3.0

stata_kernel: 1.11.2

**Machine 2**
Microsoft Windows, Version 1903 (OS Build 18362.836)
Atom setups:
apm  2.4.3
npm  6.2.0
node 10.2.1 x64
atom 1.46.0
python 2.7.15
git 2.25.0.windows.1
visual studio 2015

atom packages:
├── file-icons@2.1.41
├── highlight-selected@0.17.0
├── Hydrogen@2.14.1
├── hyperclick@0.1.5
├── indent-detective@0.4.0
├── ink@0.12.3
├── julia-client@0.12.4
├── language-batch@0.4.0
├── language-julia@0.19.3
├── language-stata@1.7.3
├── latex-completions@0.3.6
├── move-panes@0.2.0
├── script@3.26.0
├── scroll-marker@0.3.2
├── tool-bar@1.3.0
└── uber-juno@0.3.0

stata_kernel: 1.11.2

Any comments or advice are welcome. Thanks in advance.

**Comment by pierrehenry14** [comment]
I have the same issue with stata 16

**Comment by robsunch** [comment]
> I have the same issue, unfortunately I do not have a machine 2

The problem seems to be resolved after I reinstalled Hydrogen and the Stata kernel. So it could be caused by improper installation of either (or both) earlier. I basically deleted all versions of python on my computer, then installed Anaconda and the Stata kernel. When I start Atom from the Anaconda prompt, the kernel works fine.

**Comment by pierrehenry14** [comment]
> > I have the same issue, unfortunately I do not have a machine 2
> 
> The problem seems to be resolved after I reinstalled Hydrogen and the Stata kernel. So it could be caused by improper installation of either (or both) earlier. I basically deleted all versions of python on my computer, then installed Anaconda and the Stata kernel. When I start Atom from the Anaconda prompt, the kernel works fine.

I finally solved the problem by changing the folder of cache_directory.

**Comment by robsunch** [comment]
Haven't tried @pierrehenry14 's method, but I upgraded to stata_kernel  version 1.12.2 today and it is fixed!
