### ISSUE TITLE
`foreach` highlighting breaks with macro name starting with "in" or "of"

### ISSUE THREAD

**Issue by hudcap** [kylebarron/language-stata#113]
If ```foreach``` defines a macro that starts with "in" or "of," the syntax highlighting fails for that line.
MWE:
    
    foreach indepvar of varlist foo bar {
        reg dep indepvar
    }
    
PR to follow

**Comment by hudcap** [comment]
Is this repo still being maintained?
This issue and PR is 6 months old with no response.

**Comment by kylebarron** [comment]
Not really. I'm not an economist anymore, and don't have access to Stata

**Comment by hudcap** [comment]
Oh well, thanks for all the hard work you put into it!
