### ISSUE TITLE
Red highlights after brace not right

### ISSUE THREAD

**Issue by peterhickmanj** [kylebarron/language-stata#20]
This is a pretty particular context, but for my -outreg- command I need to use braces and I'd like the following text not to be highlighted yellow. Is there a way to fix this?
![issue2](https://user-images.githubusercontent.com/10004003/31041862-56fb2972-a56a-11e7-95e9-a37f62ac0cbc.PNG)

**Comment by kylebarron** [comment]
I haven't pushed it to Atom yet, but this is fixed with https://github.com/kylebarron/language-stata/commit/5cda59b0d2f138daee7f708e53bc90f0871f31d5

**Comment by kylebarron** [comment]
Fixed with https://github.com/kylebarron/language-stata/pull/23
