### ISSUE TITLE
Regex highlighting does not work if regexm after another function

### ISSUE THREAD

**Issue by peterhickmanj** [kylebarron/language-stata#21]
I first noticed this with assert(mi(code14) | regexm(code14, "^(SC|[0-9]*)C*$")), an actual use case where there was no highligting.

In general, though, the regex highlighting is awesome! You did a great job!

![issue3](https://user-images.githubusercontent.com/10004003/31041887-8f1c403e-a56a-11e7-84ec-46dcc9b22f0a.PNG)

**Comment by kylebarron** [comment]
Fixed with https://github.com/kylebarron/language-stata/pull/23
