### ISSUE TITLE
No Syntax Highlighting After -Duplicates Drop-

### ISSUE THREAD

**Issue by peterhickmanj** [kylebarron/language-stata#39]
![capture](https://user-images.githubusercontent.com/10004003/32337268-e4861ac8-bfc7-11e7-90d6-29d59cc3bc2d.PNG)

**Comment by kylebarron** [comment]
What version of the package do you have? Go to settings > Packages > language-stata and it should be at the top. Some bugfixes for `drop` were added in the latest version, 1.1.2.

![image](https://user-images.githubusercontent.com/15164633/32338531-6cb7ddde-bfcb-11e7-8f42-46979be77c73.png)
