### ISSUE TITLE
"/**/" incorrectly recognized as comment (on Atom)

### ISSUE THREAD

**Issue by stevencollinscn** [kylebarron/language-stata#55]
In Stata syntax, "/**/" can be used to add a comment or break a long line.  "/*" can be put at the end of a line and then "*/" can be put in the begin of the second line. In the way, Stata will read it as one line when you running the .do file. For example, the following two lines of command should perform the same.

keep var1 var2 var3 var4/*
*/ var5 var6

keep var1 var2 var3 var4 var5 var6

Right now, "*/ var5 var6" is recognized as a comment on Atom. The funny thing is that this issue only occurs on Atom, not Visual Studio Code. 
Btw, I'm using Stata 15.

**Comment by kylebarron** [comment]
![image](https://user-images.githubusercontent.com/15164633/32987335-9d2ab958-ccb6-11e7-9ed7-1150a87906b9.png)
Interesting. Let me debug

**Comment by kylebarron** [comment]
This should be fixed. Try updating

**Comment by stevencollinscn** [comment]
Thanks for updating man and I just tried and it works! Btw, I put a
whitespace because there is one space needed between two variables.
Otherwise, Stata will read it as var4var5. The pace could be put either at
the end of the first line or the beginning of the second.
I'm not sure it is the reason causing the issue. But, anyway. It works!

BTW, I tried Stata-exec on my Mac and it is amazing! I really wish I can
use it on my Wins. Is gotta be soon?

2017-11-18 23:17 GMT-05:00 Kyle Barron <notifications@github.com>:

**Comment by stevencollinscn** [comment]
I saw your screenshot and saw what you’re saying. The space seemed to be the issue. Lol.

**Comment by kylebarron** [comment]
No idea exactly when Windows will happen. I'm working on it, but I don't know much about Windows. I might end up basically taking the code from https://github.com/mattiasnordin/StataEditor and requiring Python as a dependency.

Tonight I got code working to run code from Mac in a Stata session that's running on a remote server. I'll publish that soon.

**Comment by stevencollinscn** [comment]
That’s exciting! The data I’m working on is too big and the memory in my Mac can’ handle it. But I do have friends who use Stata on Mac and they gotta love your work!
I actually do have python on my Wins PC. Wish to see it soon. Anyway...thanks man!

**Comment by stevencollinscn** [comment]
Hi, buddy.

Since I'm not a developer, this site doesn't make much sense for me. But is
it useful for you?

http://econwang.com/atom.html#stata

2017-11-18 23:55 GMT-05:00 Steven Collins <stevencollinscn@gmail.com>:
