### ISSUE TITLE
What's the recommended way to add custom commands?

### ISSUE THREAD

**Issue by felixholub** [kylebarron/language-stata#64]
If I install some program, say `reghdfe` (https://github.com/sergiocorreia/reghdfe) what is the best way to make the new functions get recognized? Shall I just manually update the code and add the desired command?

**Comment by kylebarron** [comment]
It's not straightforward to edit the package manually; if you edit the files in `~/.atom/packages/language-stata`, they'll be overwritten when you download an updated package version. 

The best way is really to submit a pull request or ask me to add the highlighting. `reghdfe` is a very popular add on package anyways. What exactly do you mean by getting the new functions "recognized"? Do you mean the highlighting or the autocomplete? The package already highlights all options with parentheses, like `absorb()`.

Ideally the autocomplete would be improved by only suggesting the options for the currently selected function, but that's a long way off.

**Comment by felixholub** [comment]
I was referring to syntax highlighting with "recognized". For example, `reg ...` or `gen ...` are highlighted. For the `-reghdfe-` example, there is indeed highlighting of the options, but not of the main command `reghdfe ...` itself. Other commands which do not highlight the name of the function are for example `ivreghdfe ...` or functions included in `-gtools-`.
I hope this clarifies it a little ;) If the way to go is the "official" one via pull requests, I'm happy about that solution.
(Thanks a lot by the way!)

**Comment by kylebarron** [comment]
I added `reghdfe|ivreghdfe|ivreg2|outreg|gcollapse|gcontract|gegen|gisid|glevelsof|gquantiles`. It's super easy to add more, I just don't use user-written commands all the time. If you have any more you want, just give me a list. Thanks!

**Comment by felixholub** [comment]
Great! Thanks Kyle! I'll keep a note and will open a new issue once I've collected some more commands.
