### ISSUE TITLE
Incorrect "warning" highlighting after curly brackets

### ISSUE THREAD

**Issue by acarril** [kylebarron/language-stata#80]
This is very minor, but here it goes: I see that there is some kind of "warning" highlighting after you type any text in the same line after an open curly brace, like in the following example:
![image](https://user-images.githubusercontent.com/9773292/36080792-e519ff68-0f63-11e8-82a6-25d35cae5fd3.png)

However, the highlighter is also triggered when writing text after a curly brace in situations in which this is correct, such as when using `estout`'s `prefix` option:
![image](https://user-images.githubusercontent.com/9773292/36080817-48d4efe0-0f64-11e8-843f-908dd7a3745c.png)

Maybe you could tweak the highlighter so that it only kicks in in lines starting with `foreach`, `forvalues` and `while` (or their abbreviations).

**Comment by kylebarron** [comment]
I think I should be able to fix this by turning off `{}` highlighting inside function calls. That's pretty straightforward. 

I currently have one rule set apart to deal with a specific use of {} text, but the above is much easier.

Ping me about this in a week.

**Comment by kylebarron** [comment]
Try it out with the new version
