### ISSUE TITLE
Update for tree-sitter

### ISSUE THREAD

**Issue by kylebarron** [kylebarron/language-stata#81]
A new style of language grammar will be available with Atom 1.25, called [tree-sitter](https://github.com/tree-sitter/tree-sitter). This seems to be more advanced than the current system, first-mate.

It looks like the format for the new syntax rules is currently documented here:
https://github.com/tree-sitter/tree-sitter/blob/master/doc/grammar-schema.json

The current tree-sitter version of Atom's own language-python is here:
https://github.com/atom/language-python/blob/master/grammars/tree-sitter-python.cson

See discussion here:
https://github.com/atom/atom/pull/16299

**Comment by jkyeung** [comment]
> It looks like the format for the new syntax rules is currently documented here:

That link is broken, and the documentation seems to be under construction. There is some meaningful content available now, but it may be safest to start at the docs directory:

https://github.com/tree-sitter/tree-sitter/tree/master/docs

**Comment by kylebarron** [comment]
Yeah this is the place for documentation for future reference:
https://tree-sitter.github.io/tree-sitter/
