### ISSUE TITLE
Unbracketed globals break syntax highlighting 

### ISSUE THREAD

**Issue by acarril** [kylebarron/language-stata#83]
![language-stata-bug](https://user-images.githubusercontent.com/9773292/37908564-a031e6ce-30d6-11e8-9f05-e3e89401deef.PNG)

**Comment by kylebarron** [comment]
until I fix this, add a space after `$somevars`

**Comment by kylebarron** [comment]
Is this fixed now?
![image](https://user-images.githubusercontent.com/15164633/41265060-3aa673c2-6dbe-11e8-87ab-3393c95dd46c.png)

might need to wait until next release if not
