### ISSUE TITLE
Incorrect tick marks enclosing locals

### ISSUE THREAD

**Issue by acarril** [kylebarron/language-stata#87]
It used to be possible to automatically enclose a string with "local tickmarks", i.e. `` `foo' ``, just by selecting the string and then using the `` ` `` key. But now you get double back-ticks:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/9773292/38873005-b5ddccb0-4222-11e8-8521-c44a52176ca5.gif)

**Comment by kylebarron** [comment]
That's because your file isn't saved. With the local tickmarks, that's a setting that Atom sets on a file basis. So when you open a new file, Atom automatically sets the bracket matching to the standard ``. Save it as a do file, close and open the file and it should work.
