### ISSUE TITLE
Toggle comments could support more comment styles?

### ISSUE THREAD

**Issue by karldw** [kylebarron/language-stata#88]
As always, thanks for the great Atom package!

I notice that the toggle comments only works well with Stata's `/* */` comment style, not `*` or `//`. That's fine for commenting uncommented code, but leads to surprising results when I try to uncomment code that's been commented out with `//` or `*`. 
This is a super minor issue. 

Demo:
```stata
// This works well:
gen x = 1        // before toggle comments
/* gen x = 1 */  // after toggle comments
gen x = 1        // one more toggle comments

// This is a little surprising:
* gen x = 1        // before toggle comments
/* * gen x = 1 */  // after toggle comments
// Expected:
gen x = 1          // expected uncommenting
```

**Comment by kylebarron** [comment]
See https://github.com/kylebarron/language-stata/issues/85

I don't think I can tell Atom multiple comment symbols. But I'll check that out sometime.

**Comment by kylebarron** [comment]
Yeah, I can't give Atom multiple comment characters. I'm considering changing the default to `//` though
