### ISSUE TITLE
Some corner cases for highlighting comments

### ISSUE THREAD

**Issue by mcaceresb** [kylebarron/language-stata#90]
```stata
disp /// /* ignored
"printed"
```

```stata
/**/ * disp "not printed"
```

```stata
local ninety 90
disp `ni/*comments are allowed inside locals*/nety'
disp `ni/*
/*These can be nested and span multiple lines*/
*/nety'
disp "`ninety/* Ignored but not a comment per se. Any non [0-9a-zA-Z_] character would do*/'"
disp "`ninety@This is also not evaluated, for example.'"
```

```stata
/*/ disp "printed"

/*/*
Note that /*/ opens end closes a multi-line block. And if you have a *
right after, then that opens a new one.
*/
 disp " printed"
```

**Comment by kylebarron** [comment]
I didn't realize that `///` also ignored the rest of the line like `//` did

**Comment by kylebarron** [comment]
> `/**/ * disp "not printed"`
I hadn't allowed there to be a space after a block comment and before a `*`. Easy fix.

your last example doesn't seem to work in isolation?

1:
![image](https://user-images.githubusercontent.com/15164633/41261523-09478884-6daa-11e8-8ffd-a99f3d3cb879.png)

2:
![image](https://user-images.githubusercontent.com/15164633/41261546-33baf7c2-6daa-11e8-8473-9925d930ec2e.png)

**Comment by mcaceresb** [comment]
It seems as of Stata 14, `/*/` no longer starts and ends a block. However, ending a block by `*/*` does seem to start a new block.

**Comment by kylebarron** [comment]
that last part is now fixed
![image](https://user-images.githubusercontent.com/15164633/41262331-2acc54ae-6dae-11e8-9e00-dc91f72f700f.png)

**Comment by kylebarron** [comment]
the right regex for globals should be `[A-Za-z][A-Za-z0-9_]{0,31}|_[A-Za-z0-9_]{1,31}`, even though Stata doesn't let you create a global with "global __ hi" or "global __z hi", only reference a local "_" or "_z" that's already been created.

Additionally, those aren't actually the right regexes, because we've been working only in the ASCII world. 

![image](https://user-images.githubusercontent.com/15164633/41262607-cfbaa83e-6daf-11e8-99f3-cf8969fd6539.png)

that's also a valid local.

So I have to use \w in more places. And \w&&[^\d] when I want to refer to letters but not numbers.

**Comment by mcaceresb** [comment]
Very impressive.

**Comment by kylebarron** [comment]
Switch to Atom!

**Comment by kylebarron** [comment]
[Hydrogen](https://nteract.gitbooks.io/hydrogen/) is amazing. It works so seamlessly with remote servers too.

**Comment by mcaceresb** [comment]
Well, I like the prettiness, but I don't know that i can get a ton of mileage out stuff like Hydrogen on the stuff I do daily (cool as it is). The language plugin ecosystem is more interesting (e.g. your package is certainly miles ahead the Stata package in Vim).

I wonder if marginal improvements justify the switching costs, though. Using Atom feels really slow. Other than the startup, however, Atom doesn't seem slow at all, so I'm pretty sure that it's because I don't have all the muscle memory I've built up using vim.

Modal editing is extremely functional; same for the way registers, markets, mappings, and macros work. I'm sure you can replicate most (all? more?) of that in Atom. Do I want to spent a ton of time re-learning (and, perhaps just as importantly, a ton of time porting everything)? Not yet. I wonder if it will ever reach a tipping point, though.

**Comment by kylebarron** [comment]
> disp "`ninety/* Ignored but not a comment per se. Any non [0-9a-zA-Z_] character would do*/'"
> disp "`ninety@This is also not evaluated, for example.'"


@mcaceresb It appears that `()` doesn't end a local.

```stata
sysuse auto
local ar "not printed"
di "`ar()'"
```

**Comment by mcaceresb** [comment]
Interestingly,

    disp "`ar)'"

does work.

**Comment by mcaceresb** [comment]
Interestingly, the `local ++i' convention works _within locals_ as well!

```stata
local i = 1
disp `++i'
disp `i++'
disp `i++And, amazingly, this is allowed. even though ++ is operating on the local i!'
disp `i'
```

**Comment by mcaceresb** [comment]
Actually, since locals are evaluated inside locals, you can't really call them comments:

```stata
local i 1
disp "i = `i++Locals here are evaluated. `++i', `++i', and `i++' are evaluated.'"

local i = 1
disp `i"/*`++i'*/"Does this print 1, 2, 3? /*"`++i'"*/'
```

The above prints 4 and stores 5 in the local i for the first chunk and prints 2 for the second chunk. Note that you can get errors from stuff you put here:

```stata
local j a '
disp `i#This is fine'
disp `i=`=This is a soft error''
disp `i#This is a hard error`j''
```

**Comment by kylebarron** [comment]
That's so crazy. I kinda give up on these corner cases

**Comment by mcaceresb** [comment]
I would think it is better is to leave them as part of the local. I don't think many people are putting comments or such inside locals. Locals inside locals, on the other hand, are semi-common.

**Comment by kylebarron** [comment]
Locals inside locals works as long as there aren't huge spaces
