### ISSUE TITLE
Can not use Chinese Characters when using Use the new Stata Jupyter kernel with Atom's Hydrogen package

### ISSUE THREAD

**Issue by LulinS** [kylebarron/language-stata#98]
When my code contains Chinese Characters, it always reports: UnicodeEncodeError: 'ascii' codec can't encode characters in position 43-44: ordinal not in range(128)
Full message:
> [IPKernelApp] ERROR | Exception in message handler: Traceback (most recent call last): File "/Applications/anaconda3/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 233, in dispatch_shell handler(stream, idents, msg) File "/Applications/anaconda3/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 399, in execute_request user_expressions, allow_stdin) File "/Applications/anaconda3/lib/python3.6/site-packages/stata_kernel/kernel.py", line 81, in do_execute text_to_run, md5, text_to_exclude=text_to_exclude) File "/Applications/anaconda3/lib/python3.6/site-packages/stata_kernel/stata_session.py", line 186, in do self.child.sendline(text) File "/Applications/anaconda3/lib/python3.6/site-packages/pexpect/pty_spawn.py", line 555, in sendline return self.send(s + self.linesep) File "/Applications/anaconda3/lib/python3.6/site-packages/pexpect/pty_spawn.py", line 543, in send self._log(s, 'send') File "/Applications/anaconda3/lib/python3.6/site-packages/pexpect/spawnbase.py", line 126, in _log self.logfile.write(s) UnicodeEncodeError: 'ascii' codec can't encode characters in position 43-44: ordinal not in range(128)

**Comment by kylebarron** [comment]
Can you post this on the issues for the stata_kernel repository here instead: 
https://github.com/kylebarron/stata_kernel/issues/new?template=bug_report.md

Thanks

**Comment by kylebarron** [comment]
I think this is the same error as https://github.com/pexpect/pexpect/issues/516.

**Comment by kylebarron** [comment]
@LulinS Can you try upgrading to the new version of the package?

```
pip install stata_kernel --upgrade
```

**Comment by LulinS** [comment]
> @LulinS Can you try upgrading to the new version of the package?
> 
> ```
> pip install stata_kernel --upgrade
> ```
You guys are so great! I have upgraded to the new version of the package, and partly solved the problem. But there is a still a small bug. I will report this on the issues for the stata_kernel repository.

Thanks!
